version: "3.8"

networks:
  library-network:
    driver: bridge

services:
  postgres:
    image: postgres:16.6
    container_name: imagelite
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - library-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin15
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - library-network
